Fix golangci-lint errors/warnings
```
bits/bits_benchmark_test.go:12:15: Error return value of `writer.Write` is not checked (errcheck)
		writer.Write(0xff, 8)
		           ^
mp4/avc.go:28:6: `isVideoNalu` is unused (deadcode)
func isVideoNalu(b []byte) bool {
     ^
mp4/box.go:191:6: `fixed16` is unused (deadcode)
func fixed16(bytes []byte) Fixed16 {
     ^
mp4/box.go:195:6: `putFixed16` is unused (deadcode)
func putFixed16(bytes []byte, i Fixed16) {
     ^
mp4/box.go:206:6: `fixed32` is unused (deadcode)
func fixed32(bytes []byte) Fixed32 {
     ^
mp4/box.go:210:6: `putFixed32` is unused (deadcode)
func putFixed32(bytes []byte, i Fixed32) {
     ^
mp4/trun.go:21:7: `dataOffsetPresentFlag` is unused (deadcode)
const dataOffsetPresentFlag = 0x01
      ^
mp4/audiosampleentry_test.go:14:12: Error return value of `ase.Encode` is not checked (errcheck)
	ase.Encode(&buf)
	         ^
mp4/audiosamplentry.go:144:15: Error return value of `child.Encode` is not checked (errcheck)
		child.Encode(w)
		           ^
mp4/avc.go:250:11: Error return value of `parseVUI` is not checked (errcheck)
		parseVUI(reader, &sps.VUI, true)
		       ^
mp4/avcdecoderconfigurationrecord.go:81:14: Error return value of `binary.Write` is not checked (errcheck)
	binary.Write(w, binary.BigEndian, configurationVersion)
	           ^
mp4/avcdecoderconfigurationrecord.go:82:14: Error return value of `binary.Write` is not checked (errcheck)
	binary.Write(w, binary.BigEndian, a.AVCProfileIndication)
	           ^
mp4/avcdecoderconfigurationrecord.go:83:14: Error return value of `binary.Write` is not checked (errcheck)
	binary.Write(w, binary.BigEndian, a.ProfileCompatibility)
	           ^
mp4/avcdecoderconfigurationrecord.go:91:10: Error return value of `w.Write` is not checked (errcheck)
		w.Write(sps)
		      ^
mp4/avcdecoderconfigurationrecord.go:98:10: Error return value of `w.Write` is not checked (errcheck)
		w.Write(pps)
		      ^
mp4/elng.go:52:9: Error return value of `w.Write` is not checked (errcheck)
	w.Write([]byte(b.Language))
	      ^
mp4/esds_test.go:17:15: Error return value of `esdsIn.Encode` is not checked (errcheck)
	esdsIn.Encode(&buf)
	            ^
mp4/initsegment_test.go:101:13: Error return value of `init.Encode` is not checked (errcheck)
	init.Encode(&buf)
	          ^
mp4/initsegment_test.go:119:13: Error return value of `init.Encode` is not checked (errcheck)
	init.Encode(ofd)
	          ^
mp4/mediasegment_test.go:49:27: Error return value of `.Encode` is not checked (errcheck)
	f.Segments[0].Styp.Encode(&buf)
	                        ^
mp4/mediasegment_test.go:51:14: Error return value of `frag.Encode` is not checked (errcheck)
		frag.Encode(&buf)
		          ^
mp4/mvhd_test.go:13:20: Error return value of `mvhdCreated.Encode` is not checked (errcheck)
	mvhdCreated.Encode(&buf)
	                 ^
mp4/tfdt_test.go:64:13: Error return value of `tfdt.Encode` is not checked (errcheck)
	tfdt.Encode(w)
	          ^
mp4/tfhd_test.go:28:17: Error return value of `tfhdRead.Encode` is not checked (errcheck)
	tfhdRead.Encode(outbuf)
	              ^
mp4/tkhd_test.go:13:20: Error return value of `tkhdCreated.Encode` is not checked (errcheck)
	tkhdCreated.Encode(&buf)
	                 ^
mp4/visualsampleentry.go:170:15: Error return value of `child.Encode` is not checked (errcheck)
		child.Encode(w)
		           ^
mp4/esds.go:99:2: ineffectual assignment to `size` (ineffassign)
	size, nrBytesRead := readSizeOfInstance(s)
	^
mp4/esds.go:107:2: ineffectual assignment to `size` (ineffassign)
	size, nrBytesRead = readSizeOfInstance(s)
	^
mp4/url.go:31:13: ineffectual assignment to `err` (ineffassign)
		location, err = s.ReadZeroTerminatedString()
		         ^
mp4/elng_test.go:41:5: S1030: should use buf.String() instead of string(buf.Bytes()) (gosimple)
	if string(buf.Bytes()) != elngString {
	  ^
mp4/esds_test.go:26:5: S1004: should use !bytes.Equal(decCfgOut, decCfg) instead (gosimple)
	if bytes.Compare(decCfgOut, decCfg) != 0 {
	  ^
mp4/mediasegment_test.go:59:5: S1004: should use !bytes.Equal(outFileContent, inFileContent) instead (gosimple)
	if bytes.Compare(outFileContent, inFileContent) != 0 {
	  ^
mp4/tfdt_test.go:68:5: S1004: should use !bytes.Equal(byteData, writtenBytes) instead (gosimple)
	if bytes.Compare(byteData, writtenBytes) != 0 {
	  ^
mp4/avc.go:194:50: S1019: should use make([]uint, numRefFramesInPicOrderCntCycle) instead (gosimple)
		sps.RefFramesInPicOrderCntCycle = make([]uint, numRefFramesInPicOrderCntCycle,
		                                              ^
mp4/initsegment_test.go:115:2: SA5001: should check returned error before deferring ofd.Close() (staticcheck)
	defer ofd.Close()
	^
cmd/mp4ff-pslister/main.go:35:2: SA5001: should check returned error before deferring ifd.Close() (staticcheck)
	defer ifd.Close()
	^
```